FROM metabase/metabase:VERSION
ENV MB_JETTY_PORT 8080
ENV MB_PLUGINS_DIR /plugins

WORKDIR ${MB_PLUGINS_DIR}
RUN wget https://github.com/dacort/metabase-athena-driver/releases/download/v0.2.1/athena.metabase-driver.jar

WORKDIR /app

EXPOSE 8080
